apiVersion: v1
kind: Service
metadata:
  name: testapp
  labels:
    app: testapp
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: testapp
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: testapp-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "testapp.$INGRESS_HOST.xip.io"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: testapp
spec:
  hosts:
  - "testapp.$INGRESS_HOST.xip.io"
  gateways:
  - testapp-gateway
  http:
  - route:
    - destination:
        port:
          number: 80
        host: testapp
        subset: v1
      weight: 50
    - destination:
        host: testapp
        subset: v2
      weight: 50
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: testapp-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testapp
        version: v1
    spec:
      containers:
      - name: testapp
        image: gcr.io/ikea-cloudfoundation-test/testapp:v1
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: testapp-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testapp
        version: v2
    spec:
      containers:
      - name: testapp
        image: gcr.io/ikea-cloudfoundation-test/testapp:v2
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: testapp-destination
spec:
  host: testapp # interpreted as testapp.foo.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
